# -*- coding: utf-8 -*-
"""fraud_detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XQTBNy0qKIKGF7SqN4m7Xd1sh54OdMKN
"""

# Install if needed:
# pip install pandas scikit-learn imbalanced-learn matplotlib seaborn

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from collections import Counter

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier # Changed to RandomForestClassifier

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    ConfusionMatrixDisplay
)

from imblearn.over_sampling import SMOTE


# =========================================================
# 1. Load dataset
# =========================================================

# 1. Create a cached data loader function so it only downloads the dataset once
@st.cache_data
def load_data_from_cloud():
    # TODO: Paste your direct cloud download link below
    url = "https://google.com"
    return pd.read_csv(url)

# 2. Call the cloud data loader function
df = load_data_from_cloud()

# Drop rows with any NaN values
df.dropna(inplace=True)

print("Dataset shape:", df.shape)
print(df.head())


# =========================================================
# 2. Check class distribution
# =========================================================

print("\nOriginal class distribution:")
print(df["Class"].value_counts())

print("\nPercentage:")
print(df["Class"].value_counts(normalize=True) * 100)


# Plot class distribution
sns.countplot(x="Class", data=df)
plt.title("Fraud vs Legitimate Transactions")
plt.xlabel("Class (0 = Legitimate, 1 = Fraud)")
plt.ylabel("Number of Transactions")
plt.show()


# =========================================================
# 3. Separate X and y
# =========================================================

X = df.drop("Class", axis=1)
y = df["Class"]


# =========================================================
# 4. Train/Test Split
# =========================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nBefore SMOTE:")
print(Counter(y_train))


# =========================================================
# 5. Scale numerical features
# =========================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# =========================================================
# 6. Apply SMOTE ONLY to training data
# =========================================================

smote = SMOTE(
    sampling_strategy=1.0,
    random_state=42
)

X_train_balanced, y_train_balanced = smote.fit_resample(
    X_train_scaled,
    y_train
)

print("\nAfter SMOTE:")
print(Counter(y_train_balanced))


# =========================================================
# 7. Train Random Forest
# =========================================================

model = RandomForestClassifier( # Changed to RandomForestClassifier
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(
    X_train_balanced,
    y_train_balanced
)


# =========================================================
# 8. Prediction
# =========================================================

y_pred = model.predict(X_test_scaled)

y_probability = model.predict_proba(X_test_scaled)[:, 1]


# =========================================================
# 9. Evaluation
# =========================================================

print("\nClassification Report:")
print(classification_report(y_test, y_pred))


# ROC-AUC
roc_auc = roc_auc_score(
    y_test,
    y_probability
)

print("ROC-AUC:", roc_auc)


# =========================================================
# 10. Confusion Matrix
# =========================================================

cm = confusion_matrix(
    y_test,
    y_pred
)

print("\nConfusion Matrix:")
print(cm)

ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Legitimate", "Fraud"]
).plot()

plt.title("Fraud Detection Confusion Matrix")
plt.show()

# =========================================================
# 11. Feature Importance
# =========================================================

feature_importances = pd.Series(model.feature_importances_, index=X.columns)

plt.figure(figsize=(12, 6))
feature_importances.nlargest(10).plot(kind='barh')
plt.title('Top 10 Feature Importances (Random Forest)')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.show()

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import pandas as pd

print("\n=========================================================")
print("Building and Evaluating Decision Tree Classifier")
print("=========================================================\n")

# 1. Train Decision Tree
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train_balanced, y_train_balanced)

# 2. Prediction with Decision Tree
dt_y_pred = dt_model.predict(X_test_scaled)
dt_y_probability = dt_model.predict_proba(X_test_scaled)[:, 1]

# 3. Evaluation for Decision Tree
print("\nDecision Tree Classification Report:")
print(classification_report(y_test, dt_y_pred))

dt_roc_auc = roc_auc_score(y_test, dt_y_probability)
print("Decision Tree ROC-AUC:", dt_roc_auc)

dt_cm = confusion_matrix(y_test, dt_y_pred)
print("\nDecision Tree Confusion Matrix:")
print(dt_cm)

ConfusionMatrixDisplay(
    confusion_matrix=dt_cm,
    display_labels=["Legitimate", "Fraud"]
).plot()
plt.title("Decision Tree Fraud Detection Confusion Matrix")
plt.show()

# 4. Compare Model Performance

# Assuming 'model' (RandomForestClassifier) and its metrics (y_pred, y_probability, roc_auc, cm) are available from the previous cell.

# Get metrics for Random Forest (from previous cell's output)
rf_report = classification_report(y_test, y_pred, output_dict=True)
rf_accuracy = rf_report['accuracy']
rf_precision_fraud = rf_report['1']['precision']
rf_recall_fraud = rf_report['1']['recall']
rf_f1_fraud = rf_report['1']['f1-score']
rf_roc_auc = roc_auc # Already calculated as 'roc_auc'

# Get metrics for Decision Tree
dt_report = classification_report(y_test, dt_y_pred, output_dict=True)
dt_accuracy = dt_report['accuracy']
dt_precision_fraud = dt_report['1']['precision']
dt_recall_fraud = dt_report['1']['recall']
dt_f1_fraud = dt_report['1']['f1-score']
# dt_roc_auc is already calculated for Decision Tree

comparison_data = {
    'Model': ['Random Forest', 'Decision Tree'],
    'Accuracy': [rf_accuracy, dt_accuracy],
    'Fraud Precision': [rf_precision_fraud, dt_precision_fraud],
    'Fraud Recall': [rf_recall_fraud, dt_recall_fraud],
    'Fraud F1-Score': [rf_f1_fraud, dt_f1_fraud],
    'ROC-AUC': [rf_roc_auc, dt_roc_auc]
}

performance_df = pd.DataFrame(comparison_data)
print("\n=========================================================")
print("Model Performance Comparison")
print("=========================================================")
print(performance_df.round(4).to_markdown(index=False))

# 5. Feature Importance for Decision Tree
dt_feature_importances = pd.Series(dt_model.feature_importances_, index=X.columns)

plt.figure(figsize=(12, 6))
dt_feature_importances.nlargest(10).plot(kind='barh')
plt.title('Top 10 Feature Importances (Decision Tree)')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

# Feature Importance for Random Forest Model (from 'model' object)
feature_importances_rf = pd.Series(model.feature_importances_, index=X.columns)

plt.figure(figsize=(12, 6))
feature_importances_rf.nlargest(10).plot(kind='barh', color='skyblue')
plt.title('Top 10 Feature Importances (Random Forest)')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.gca().invert_yaxis() # Display highest importance at the top
plt.show()

# Feature Importance for Decision Tree Model (from 'dt_model' object)
dt_feature_importances_dt = pd.Series(dt_model.feature_importances_, index=X.columns)

plt.figure(figsize=(12, 6))
dt_feature_importances_dt.nlargest(10).plot(kind='barh', color='lightcoral')
plt.title('Top 10 Feature Importances (Decision Tree)')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.gca().invert_yaxis() # Display highest importance at the top
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
# 
# from collections import Counter
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.metrics import (
#     classification_report,
#     confusion_matrix,
#     roc_auc_score,
#     ConfusionMatrixDisplay
# )
# from imblearn.over_sampling import SMOTE
# import numpy as np
# 
# # --- Configuration / Global Parameters ---
# DATA_FILE = "creditcard.csv"
# RANDOM_STATE = 42
# TEST_SIZE = 0.2
# N_ESTIMATORS_RF = 100
# 
# # --- Helper Functions (for a self-contained app) ---
# 
# @st.cache_data
# def load_and_preprocess_data(file_path):
#     """Loads the dataset, drops NaNs, and splits into features (X) and target (y)."""
#     try:
#         df = pd.read_csv(file_path)
#         df.dropna(inplace=True)
#         X = df.drop("Class", axis=1)
#         y = df["Class"]
#         return X, y, df
#     except FileNotFoundError:
#         st.error(f"Error: The file '{file_path}' was not found. Please ensure it's in the same directory as the app.")
#         st.stop()
#     except Exception as e:
#         st.error(f"An error occurred during data loading or preprocessing: {e}")
#         st.stop()
# 
# @st.cache_resource # Cache the trained models
# def train_and_evaluate_models(X_full, y_full):
#     """Trains Random Forest and Decision Tree models and returns their metrics and objects."""
#     X_train, X_test, y_train, y_test = train_test_split(
#         X_full, y_full, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y_full
#     )
# 
#     scaler = StandardScaler()
#     X_train_scaled = scaler.fit_transform(X_train)
#     X_test_scaled = scaler.transform(X_test)
# 
#     smote = SMOTE(sampling_strategy=1.0, random_state=RANDOM_STATE)
#     X_train_balanced, y_train_balanced = smote.fit_resample(X_train_scaled, y_train)
# 
#     # --- Random Forest ---
#     rf_model = RandomForestClassifier(n_estimators=N_ESTIMATORS_RF, random_state=RANDOM_STATE, n_jobs=-1)
#     rf_model.fit(X_train_balanced, y_train_balanced)
#     rf_y_pred = rf_model.predict(X_test_scaled)
#     rf_y_probability = rf_model.predict_proba(X_test_scaled)[:, 1]
#     rf_roc_auc = roc_auc_score(y_test, rf_y_probability)
#     rf_report_dict = classification_report(y_test, rf_y_pred, output_dict=True)
#     rf_cm = confusion_matrix(y_test, rf_y_pred)
#     rf_feature_importances = pd.Series(rf_model.feature_importances_, index=X_full.columns)
# 
#     # --- Decision Tree ---
#     dt_model = DecisionTreeClassifier(random_state=RANDOM_STATE)
#     dt_model.fit(X_train_balanced, y_train_balanced)
#     dt_y_pred = dt_model.predict(X_test_scaled)
#     dt_y_probability = dt_model.predict_proba(X_test_scaled)[:, 1]
#     dt_roc_auc = roc_auc_score(y_test, dt_y_probability)
#     dt_report_dict = classification_report(y_test, dt_y_pred, output_dict=True)
#     dt_cm = confusion_matrix(y_test, dt_y_pred)
#     dt_feature_importances = pd.Series(dt_model.feature_importances_, index=X_full.columns)
# 
#     # Prepare comparison data
#     comparison_data = {
#         'Model': ['Random Forest', 'Decision Tree'],
#         'Accuracy': [rf_report_dict['accuracy'], dt_report_dict['accuracy']],
#         'Fraud Precision': [rf_report_dict['1.0']['precision'], dt_report_dict['1.0']['precision']],
#         'Fraud Recall': [rf_report_dict['1.0']['recall'], dt_report_dict['1.0']['recall']],
#         'Fraud F1-Score': [rf_report_dict['1.0']['f1-score'], dt_report_dict['1.0']['f1-score']],
#         'ROC-AUC': [rf_roc_auc, dt_roc_auc]
#     }
#     performance_df = pd.DataFrame(comparison_data)
# 
#     return (rf_model, dt_model, scaler, X_test_scaled, y_test,
#             rf_y_pred, rf_y_probability, rf_roc_auc, rf_cm, rf_feature_importances,
#             dt_y_pred, dt_y_probability, dt_roc_auc, dt_cm, dt_feature_importances,
#             performance_df)
# 
# # --- Streamlit App Layout ---
# st.set_page_config(layout="wide", page_title="Fraud Detection Dashboard")
# 
# st.title("Credit Card Fraud Detection Dashboard")
# st.markdown("""
# This dashboard compares the performance of a **Random Forest Classifier** and a **Decision Tree Classifier**
# on a credit card fraud detection dataset. The models are trained with SMOTE oversampling to handle class imbalance.
# """)
# 
# X, y, df_original = load_and_preprocess_data(DATA_FILE)
# 
# (rf_model, dt_model, scaler, X_test_scaled, y_test,
#  rf_y_pred, rf_y_probability, rf_roc_auc, rf_cm, rf_feature_importances,
#  dt_y_pred, dt_y_probability, dt_roc_auc, dt_cm, dt_feature_importances,
#  performance_df) = train_and_evaluate_models(X, y)
# 
# # --- Model Comparison Section ---
# st.header("1. Model Performance Comparison")
# st.dataframe(performance_df.round(4).set_index('Model')) # Set Model as index for better display
# 
# st.markdown("---")
# 
# # --- Confusion Matrices Section ---
# st.header("2. Confusion Matrices")
# col1_cm, col2_cm = st.columns(2)
# 
# with col1_cm:
#     st.subheader("Random Forest")
#     fig_rf_cm, ax_rf_cm = plt.subplots(figsize=(6, 6))
#     ConfusionMatrixDisplay(confusion_matrix=rf_cm, display_labels=["Legitimate", "Fraud"]).plot(ax=ax_rf_cm, cmap='Blues')
#     ax_rf_cm.set_title("Random Forest Confusion Matrix")
#     st.pyplot(fig_rf_cm)
# 
# with col2_cm:
#     st.subheader("Decision Tree")
#     fig_dt_cm, ax_dt_cm = plt.subplots(figsize=(6, 6))
#     ConfusionMatrixDisplay(confusion_matrix=dt_cm, display_labels=["Legitimate", "Fraud"]).plot(ax=ax_dt_cm, cmap='Oranges')
#     ax_dt_cm.set_title("Decision Tree Confusion Matrix")
#     st.pyplot(fig_dt_cm)
# 
# st.markdown("---")
# 
# # --- Feature Importances Section ---
# st.header("3. Feature Importances")
# col1_fi, col2_fi = st.columns(2)
# 
# with col1_fi:
#     st.subheader("Random Forest Feature Importances")
#     fig_rf_fi, ax_rf_fi = plt.subplots(figsize=(8, 6))
#     rf_feature_importances.nlargest(10).plot(kind='barh', color='skyblue', ax=ax_rf_fi)
#     ax_rf_fi.set_title('Top 10 Feature Importances (Random Forest)')
#     ax_rf_fi.set_xlabel('Importance')
#     ax_rf_fi.set_ylabel('Feature')
#     ax_rf_fi.invert_yaxis()
#     st.pyplot(fig_rf_fi)
# 
# with col2_fi:
#     st.subheader("Decision Tree Feature Importances")
#     fig_dt_fi, ax_dt_fi = plt.subplots(figsize=(8, 6))
#     dt_feature_importances.nlargest(10).plot(kind='barh', color='lightcoral', ax=ax_dt_fi)
#     ax_dt_fi.set_title('Top 10 Feature Importances (Decision Tree)')
#     ax_dt_fi.set_xlabel('Importance')
#     ax_dt_fi.set_ylabel('Feature')
#     ax_dt_fi.invert_yaxis()
#     st.pyplot(fig_dt_fi)
# 
# st.markdown("---")
# 
# # --- Deployment Instructions ---
# st.subheader("How to deploy and run this Streamlit app:")
# st.markdown(f"""
# To run this application, save the code above into a Python file (e.g., `app.py`).
# Ensure the `{DATA_FILE}` dataset is in the same directory as `app.py`.
# 
# You'll need to install the required libraries:
# """)
# st.code("""
# pip install streamlit pandas scikit-learn imbalanced-learn matplotlib seaborn
# """)
# st.markdown("""
# Then, open your terminal or command prompt, navigate to the directory where you saved `app.py`, and run:
# """)
# st.code("""
# streamlit run app.py
# """)
# st.markdown("""
# This will open the application in your web browser.
# 
# **Note:** Running this cell directly in Google Colab will not launch the Streamlit web application.
# The code provided here is intended to be a standalone Streamlit application file (`.py`) for deployment.
# """)

